// ==UserScript==
// @name         Yad2 → מפת דירות
// @namespace    apartment-hunting
// @version      1.0
// @description  Extracts a yad2 listing and copies it (as apartment JSON) to the clipboard, ready for the app's "ייבוא מ-yad2 → קרא מהלוח". Works on desktop and Firefox for Android (via Violentmonkey/Tampermonkey).
// @match        https://www.yad2.co.il/realestate/item/*
// @run-at       document-idle
// @grant        none
// ==/UserScript==
(function () {
  'use strict';

  // ── Same defensive extractor as import-yad2.js / the bookmarklet ──────────
  function allObjects(root){var out=[],seen=new Set();(function rec(o){if(!o||typeof o!=='object'||seen.has(o))return;seen.add(o);out.push(o);for(var k in o)rec(o[k]);})(root);return out;}
  function resolveText(v){if(v==null)return null;if(typeof v==='string')return v.trim()||null;if(typeof v==='number')return isFinite(v)?v:null;if(typeof v==='object'){var ks=['text','name','value','title','he','hebrew','label','number','num'];for(var i=0;i<ks.length;i++){var r=resolveText(v[ks[i]]);if(r!=null)return r;}}return null;}
  function findByKeys(objs,keys,opts){opts=opts||{};var set={};keys.forEach(function(k){set[k.toLowerCase()]=1;});for(var i=0;i<objs.length;i++){var o=objs[i];for(var k in o){if(!set[k.toLowerCase()])continue;var val=resolveText(o[k]);if(val==null)continue;if(opts.number){var n=typeof val==='number'?val:parseInt(String(val).replace(/[^\d]/g,''),10);if(!isFinite(n))continue;if(opts.min!=null&&n<opts.min)continue;if(opts.max!=null&&n>opts.max)continue;return n;}return val;}}return null;}
  function findCoords(objs){for(var i=0;i<objs.length;i++){var o=objs[i],lat=null,lng=null;for(var k in o){var lk=k.toLowerCase(),val=o[k];var n=typeof val==='number'?val:(typeof val==='string'&&/^-?\d+\.\d+$/.test(val)?parseFloat(val):null);if(n==null)continue;if(lk==='lat'||lk==='latitude')lat=n;else if(lk==='lng'||lk==='lon'||lk==='long'||lk==='longitude')lng=n;}if(lat!=null&&lng!=null&&lat>29&&lat<34&&lng>34&&lng<36)return[lat,lng];}return null;}

  function extract() {
    var roots = [];
    var nd = document.getElementById('__NEXT_DATA__');
    if (nd) { try { roots.push(JSON.parse(nd.textContent)); } catch (e) {} }
    if (window.__NEXT_DATA__) roots.push(window.__NEXT_DATA__);
    document.querySelectorAll('script[type="application/ld+json"]').forEach(function (s) { try { roots.push(JSON.parse(s.textContent)); } catch (e) {} });
    var objs = [];
    roots.forEach(function (r) { objs = objs.concat(allObjects(r)); });

    var street = findByKeys(objs, ['street','streetname','street_name','streetaddress']);
    var house  = findByKeys(objs, ['housenumber','house_number','house','streetnumber','building']);
    var city   = findByKeys(objs, ['city','cityname','city_name','settlement','addresslocality']);
    var hood   = findByKeys(objs, ['neighborhood','neighbourhood','neighborhoodname','area','areaname']);
    var price  = findByKeys(objs, ['price'], { number:true, min:500, max:500000 });
    var rooms  = findByKeys(objs, ['rooms','roomscount','rooms_count','numberofrooms'], { number:true, min:1, max:30 });
    var floor  = findByKeys(objs, ['floor','floornumber','floor_number'], { number:true, min:-2, max:120 });
    var size   = findByKeys(objs, ['squaremeter','square_meters','squaremeters','sqm','builtuparea','area_size','floorsize'], { number:true, min:5, max:2000 });
    var coords = findCoords(objs);

    var address = [street, house].filter(function (v) { return v != null && v !== ''; }).join(' ').trim();
    var details = [rooms!=null?rooms+" חד'":null, size!=null?size+' מ"ר':null, floor!=null?'קומה '+floor:null].filter(Boolean).join(' · ');
    var apt = {};
    if (address) apt.address = address;
    if (city) apt.city = String(city);
    if (typeof price === 'number') apt.price = price;
    if (coords) apt.coords = coords;
    if (hood) apt.neighborhood = String(hood);
    if (details) apt.details = details;
    apt.link = location.href.split('?')[0];
    apt.status = 'interested';
    apt.autoGenerated = true;
    return apt;
  }

  function copy(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text);
    }
    return new Promise(function (res, rej) {
      var ta = document.createElement('textarea');
      ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0';
      document.body.appendChild(ta); ta.select();
      var ok = document.execCommand('copy'); document.body.removeChild(ta);
      ok ? res() : rej();
    });
  }

  function toast(msg, bg) {
    var t = document.createElement('div');
    t.textContent = msg;
    t.style.cssText = 'position:fixed;bottom:80px;left:50%;transform:translateX(-50%);background:' + (bg || '#111827') +
      ';color:#fff;padding:10px 16px;border-radius:10px;font:14px Rubik,system-ui,sans-serif;z-index:2147483647;max-width:90vw;text-align:center;box-shadow:0 4px 16px rgba(0,0,0,.3);direction:rtl;';
    document.body.appendChild(t);
    setTimeout(function () { t.remove(); }, 3500);
  }

  function onClick() {
    try {
      var apt = extract();
      var json = JSON.stringify(apt);
      var missing = ['address','city','price','coords'].filter(function (k) { return apt[k] == null; });
      copy(json).then(function () {
        toast('הועתק ✓' + (missing.length ? '  (חסר: ' + missing.join(', ') + ')' : ''), missing.length ? '#b45309' : '#059669');
      }, function () {
        prompt('העתק ידנית:', json);
      });
    } catch (e) {
      toast('חילוץ נכשל', '#dc2626');
    }
  }

  var btn = document.createElement('button');
  btn.textContent = '➕ ייבא דירה';
  btn.style.cssText = 'position:fixed;bottom:20px;left:20px;z-index:2147483647;background:#4f46e5;color:#fff;border:none;' +
    'padding:12px 18px;border-radius:999px;font:700 15px Rubik,system-ui,sans-serif;box-shadow:0 4px 14px rgba(79,70,229,.5);cursor:pointer;';
  btn.addEventListener('click', onClick);
  document.body.appendChild(btn);
})();
